name: Dependabot Test Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  contents: read
  id-token: write

jobs:
  test-build:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'

      - name: Install Dependencies
        run: |
          npm i -g yarn
          yarn setup-full

      - name: Build Production
        run: yarn build-full
        env:
          CGO_ENABLED: 1
